package li.cil.oc.api.event;

import li.cil.oc.api.internal.Agent;

/**
 * Base interface for events generated by robots.
 */
public interface RobotEvent extends Event {
    /**
     * The robot for which this event was fired.
     */
    @SuppressWarnings("unused")
    Agent agent();
}
