org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# Minecraft / toolchain
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# NeoForge
neo_version=21.1.230
neo_version_range=[21,)
loader_version_range=[1,)
# Mod
mod_id=opencomputers
mod_name=OpenComputers
mod_license=MIT
mod_version=1.10.0
mod_group_id=li.cil.oc
# OC repack libraries
jnlua_version=20230530.0
luaj_version=20220907.1
jnlua_natives_version=20220928.1
typesafe_config_version=1.4.8
# Integration / dependency mods
pr_version=4.22.0
cc_version=1.120.0
mekanism_version=10.7.19.85
enderio_version=8.2.11-beta
jei_version=19.27.0.343
wthit_version=neo-12.10.2
top_version=1.21_neo-12.0.8-7
jade_version=15.10.5+neoforge
create_version=6.0.11-292
ae2_version=19.2.17
appmek_version=1.6.3
codechickenlib_version=4.6.1.526
cbmultipart_version=3.5.0.161
enderstorage_version=2.13.0.191
railcraft_version=1.2.10
rftools_base_version=1.21-6.0.11
rftools_utility_version=1.21-7.0.12
mcjtylib_version=1.21-9.0.21
kotlinforforge_version=5.11.0
