pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
    }
}

rootProject.name = 'OpenComputers'
include 'api'
include 'core-api'
include 'core'
include 'neoforge'
include 'fabric'
include 'neoforge-api'
include 'fabric-api'
