plugins {
    id 'net.neoforged.moddev'
    id 'java-library'
}

base {
    archivesName = mod_id + "-core-1.21.1"
}

neoForge {
    neoFormVersion = "1.21.1-20240808.144430"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
    implementation(project(':api'))
    implementation(project(':core-api'))
    implementation files(rootProject.tasks.named('relocateTypesafe'))
    implementation("li.cil.repack:OC-LuaJ:${luaj_version}")
    compileOnly("li.cil.repack:OC-JNLua:${jnlua_version}")
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-common-api:${cc_version}")
    compileOnly("maven.modrinth:tis3d:MC1.21.1-neoforge-${tis3d_version}")
    compileOnly("dev.architectury:architectury-neoforge:${architectury_version}")
}
