plugins {
    id 'net.neoforged.moddev'
    id 'java-library'
}

base {
    archivesName = mod_id + "-neoforge-api"
}

neoForge {
    version = neo_version
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
    compileOnly(project(':api'))
    compileOnly(project(':core-api'))
    compileOnly(project(':core'))
}

java {
    withSourcesJar()
    withJavadocJar()
}