# NeoForge
neo_version=21.1.248
neo_version_range=[21,)
loader_version_range=[1,)
# Integration / dependency mods
pr_version=4.23.0
mekanism_version=10.7.19.85
morered_version=6.0.0.3
enderio_version=8.2.11-beta
top_version=1.21_neo-12.0.8-7
create_version=6.0.10-281
ae2_version=19.2.17
appmek_version=1.6.3
rs2_version=2.0.9
rs2mekanism_version=1.1.1
codechickenlib_version=4.6.1.526
cbmultipart_version=3.5.0.155
enderstorage_version=2.13.0.191
rftools_base_version=1.21-6.0.11
rftools_utility_version=1.21-7.0.12
mcjtylib_version=1.21-9.0.21
kotlinforforge_version=5.11.0
