plugins {
    id 'net.neoforged.moddev'
    id 'java-library'
}

base {
    archivesName = mod_id + "-api"
}

neoForge {
    neoFormVersion = "1.21.1-20240808.144430"
}

configurations {
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
    implementation files(rootProject.tasks.named('relocateTypesafe'))
}

java {
    withSourcesJar()
    withJavadocJar()
}
