name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: JDK setup
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: '21'

      - name: Build jars
        run: ./gradlew :neoforge:jar :fabric:remapJar :api:jar :neoforge-api:jar :fabric-api:remapJar --no-daemon

      - name: Upload mod jars
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: opencomputers-mod-jars
          path: |
            neoforge/build/libs/*.jar
            fabric/build/libs/*.jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload API jars
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: opencomputers-api-jars
          path: |
            api/build/libs/*.jar
            neoforge-api/build/libs/*.jar
            fabric-api/build/libs/*.jar
          if-no-files-found: error
          retention-days: 14
